### ISSUE TITLE
Upgrade `actions/cache` to latest version

### ISSUE THREAD

**Issue by pmatsinopoulos** [talentprotocol/contracts#107]
> Your workflow is using a version of actions/cache that is scheduled for deprecation, actions/cache@v2. Please update your workflow to use the latest version of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/

**Comment by susumutomita** [comment]
Hello,

I wanted to let you know that I have submitted a pull request [#110 ]addressing the deprecation notice mentioned in this issue.

The pull request updates the GitHub Actions workflow to use the latest major versions of the actions:

- Upgraded `actions/checkout` from `v2` to `v4`
- Upgraded `actions/setup-node` from `v2` to `v4`
- Upgraded `actions/cache` from `v2` to `v4`

I have included detailed explanations and references in the pull request description to clarify the changes and the reasoning behind specifying only the major versions.

Please feel free to review the pull request at your convenience. If you have any questions or need any adjustments, I'm more than happy to help.

Thank you for your time and consideration!

Best regards,

Susumu

**Comment by pmatsinopoulos** [comment]
Fixed with https://github.com/talentprotocol/contracts/pull/110
