### ISSUE TITLE
Use more advanced solhint rules

### ISSUE THREAD

**Issue by pmatsinopoulos** [talentprotocol/contracts#97]
Currently, we only use the default two:max-line-length & no-console

We may want to think about using more advanced rules like:

https://github.com/protofire/solhint/blob/HEAD/docs/rules.md

**Comment by susumutomita** [comment]
@pmatsinopoulos 
I hope this message finds you well. I wanted to let you know that I've submitted a pull request (#106) to enhance our linting configuration and scripts. When you have a moment, could you please take a look? Your feedback would be greatly appreciated.
